name: GitHub Actions PR Modified
on:
  pull_request:
    types: [edited]

jobs:
  PR-Edited:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Howdie!**
      - run: npm install
      - run: npm test
