name: GitHub Actions PR
on:
  pull_request:
    types: [edited]

jobs:
  PR-Edited:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
