name: GitHub Actions PR Modified
on:
  pull_request:
    types: [edited]
  pull_request_review_comment:
    types: [created]

jobs:
  PR-Edited:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.TEST_TOKEN }}
          message: |
            CI Comment 2
      - run: npm install
      - run: npm test
        if: ${{ failure() }}
      - uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.TEST_TOKEN }}
          message: |
            Testing failed. Please check and try again.
