name: GitHub Actions PR
on:
  pull_request:
    types: [opened,edited]

jobs:
  PR-Action:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "failed=0" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.TEST_TOKEN }}
          message: |
            PR Action in progress
          allow-repeats: true
      - name: install-node-modules
        run: npm install
      
      - name: mocha-npm-test
        run: npm test
        if: ${{ failure() }} | echo "failed=1" >> $GITHUB_ENV
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.TEST_TOKEN }}
          message: |
            Testing failed.
          allow-repeats: true
      - run: echo "exit ${{ env.failed }}"
